# Generated by Django 3.0.3 on 2021-05-29 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Uuid')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duracion', models.FloatField(blank=True, null=True, verbose_name='Duracion de la preparacion')),
                ('dificultad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dificultad de la receta')),
                ('ingredientes', models.ManyToManyField(blank=True, related_name='Ingredientes', to='products.Product')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'recipes',
                'ordering': ['id'],
            },
        ),
    ]
