# Generated by Django 3.0.3 on 2021-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_recipe'),
        ('recipes', '0002_remove_recipe_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='Ingredientes', to='products.Product'),
        ),
    ]
